name: interact
description: A collection of customizable interactive command-line components.
version: 2.2.0
repository: https://github.com/frencojobs/interact

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  dart_console:
  meta:
  tint:

dev_dependencies:
  lint:
  test:
