name: clyde
description: A collection of interactive command-line components.
version: 1.0.0
repository: https://github.com/frencojobs/clyde

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  dart_console: ^0.6.2
  tint: ^1.0.0

dev_dependencies:
  import_sorter: ^4.4.1
  lint: ^1.3.0
  test: ^1.14.4

scripts:
  sort:
    imports: pub run import_sorter:main
